brand:              /images/logo/logo_square.jpg

url:                https://intelligent-systems-phystech.github.io
edit:               https://github.com/Intelligent-Systems-Phystech/intelligent-systems-phystech.github.io/edit/
baseurl:
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Sass
sass:
  style:            :compressed

exclude: ["LICENSE", "README.md", "Gemfile", "Gemfile.lock", "vendor"]

# Highlighter
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages: ["en", "ru"]

exclude_from_localizations: ["images", "style.css", "favicon.ico", "css", "javascript"]

default_locale_in_subfolder: False

# Navigation
nav:
  pages:
  - id: "home"
    href: "/"
    name: site.nav.names.home
    dropdown:
  - id: "about"
    href: "/about"
    name: site.nav.names.about
    dropdown:
  - id: "lecturers"
    href: "/people"
    name: site.nav.names.lecturers
    dropdown:
  - id: "courses"
    href: "/course"
    name: site.nav.names.courses
    dropdown:
  - id: "applicants"
    href: "/applicants"
    name: site.nav.names.applicants
    dropdown:
  - id: "materials"
    href: "/materials"
    name: site.nav.names.materials
    dropdown:
    - id: "nir"
      href: "/materials/nir"
      name: site.nav.names.nir
    - id: "templates"
      href: "/materials/templates"
      name: site.nav.names.templates

# Scopes
defaults:
  - scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "materials"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "applicants"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"
  - scope:
      path:         ""
      type:         "course"
    values:
      layout:       "course"

collections:
  people:
    output: true
    permalink: /people/:title/index.html
  course:
    output: true
    permalink: /course/:title/index.html


global:
  langs:
    ru: Русский
    en: English

  course:
    types:
    - bachelor
    - master

  people:
    roles:
    - hotd
    - dos
    - phd
    - gs
    - teachers
    - template